name: Website

on:
  workflow_dispatch:
  push:
    paths:
      - "website/**"
      - "bun.lockb"
      - ".github/workflows/website.yaml"

jobs:
  build:
    name: Build Website

    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup | Install Dependencies
        run: bun install

      - name: Build | Astro Build
        run: bun run build
        working-directory: website

      - name: Upload | Web
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: website/dist

  publish:
    name: Publish to Cloudflare Pages

    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: website
          path: website/dist

      - name: Publish | Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: holly-landing
          directory: website/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}